# Generated by Django 5.1.1 on 2025-02-04 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_customuser_agree_to_terms_customuser_middle_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('start_location', models.CharField(help_text="Строка с координатами: 'lat,lon'", max_length=255)),
                ('end_location', models.CharField(help_text="Строка с координатами: 'lat,lon'", max_length=255)),
                ('trip_duration', models.CharField(help_text='Длительность поездки в формате HH:MM:SS', max_length=20)),
                ('route_distance', models.CharField(blank=True, help_text="Протяжённость маршрута, например, '10 км'", max_length=50, null=True)),
                ('route_duration', models.CharField(blank=True, help_text="Время в пути по данным маршрута, например, '15 мин'", max_length=50, null=True)),
                ('weather_description', models.CharField(blank=True, help_text="Описание погоды, например, 'облачно'", max_length=255, null=True)),
                ('weather_temperature', models.CharField(blank=True, help_text="Температура, например, '15°C'", max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
